/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'bg-app': 'var(--bg-app)',
        'bg-card': 'var(--bg-card)',
        'bg-sunken': 'var(--bg-sunken)',
        'bg-overlay': 'var(--bg-overlay)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'text-disabled': 'var(--text-disabled)',
        'text-inverse': 'var(--text-inverse)',
        'accent-50': 'var(--accent-50)',
        'accent-600': 'var(--accent-600)',
        'accent-700': 'var(--accent-700)',
        'brand-50': 'var(--brand-50)',
        'brand-600': 'var(--brand-600)',
        'success-50': 'var(--success-50)',
        'success-600': 'var(--success-600)',
        'warning-50': 'var(--warning-50)',
        'warning-600': 'var(--warning-600)',
        'danger-50': 'var(--danger-50)',
        'danger-600': 'var(--danger-600)',
        'border-soft': 'var(--border-soft)',
        'border-strong': 'var(--border-strong)',
        'border-focus': 'var(--border-focus)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
      },
      spacing: {
        0: '0px',
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        14: '56px',
      },
      borderRadius: {
        input: '12px',
        button: '14px',
        card: '16px',
        sheet: '20px',
        pill: '999px',
      },
      fontSize: {
        'display-xl': [
          '28px',
          { lineHeight: '34px', fontWeight: '700', letterSpacing: '-0.01em' },
        ],
        'display-lg': [
          '24px',
          { lineHeight: '30px', fontWeight: '700', letterSpacing: '-0.01em' },
        ],
        'heading-lg': [
          '20px',
          { lineHeight: '26px', fontWeight: '600', letterSpacing: '-0.005em' },
        ],
        'heading-md': ['17px', { lineHeight: '22px', fontWeight: '600' }],
        'heading-sm': ['15px', { lineHeight: '20px', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '500' }],
        caption: [
          '12px',
          { lineHeight: '16px', fontWeight: '500', letterSpacing: '0.005em' },
        ],
        micro: [
          '11px',
          { lineHeight: '14px', fontWeight: '600', letterSpacing: '0.04em' },
        ],
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI Variable"',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          'sans-serif',
        ],
      },
    },
  },
  plugins: [],
};
